name: CI Build

on: [pull_request]

env:
  LC_ALL: en_US.UTF-8

jobs:
  CheckSourceFormatting:
    name: Check source formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout liferay-ide
        uses: actions/checkout@v2
      - name: Checkout liferay-ide-m2-repository
        uses: actions/checkout@v2
        with:
          repository: gamerson/liferay-ide-m2-repository
          path: liferay-ide-m2-repository
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
      - name: sf.sh
        shell: bash
        working-directory: build/com.liferay.ide.build.source.formatter
        run: |
          ./csf.sh
  Verify:
    name: Verify
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout liferay-ide
        uses: actions/checkout@v2
      - name: Checkout liferay-ide-m2-repository
        uses: actions/checkout@v2
        with:
          repository: gamerson/liferay-ide-m2-repository
          path: liferay-ide-m2-repository
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
          cache: maven

      - name: Cache
        uses: actions/cache@v4
        with:
          path: liferay-ide-m2-repository/.cache/download-maven-plugin
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        shell: bash
        run: |
          ./run-tests.sh